name: Build and deploy SPFx solution

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "${{ (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/heads/hotfix')) && 'production' || github.ref == 'refs/heads/develop' && 'staging' || contains(github.ref, 'refs/heads/release') && 'preproduction' || contains(github.ref, 'refs/heads/feature' && 'dev')  }}"    
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: "6.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0

      - name: Install dependencies
        run: npm ci

      - name: Version solution
        run: gulp version --newversion ${{ steps.gitversion.outputs.majorMinorPatch }}
      
      - name: Bundle solution
        run: gulp bundle --ship

      - name: Package solution
        run: gulp package-solution --ship
          
      - name: Deploy to tenant app catalog
        working-directory: ./sharepoint/solution
        env: # Set the secret as an input
          CERTIFICATE_VALUE: ${{ secrets.ENV_spDeployAppCertificateValue }}
          CERTIFICATE_THUMBPRINT: ${{ secrets.ENV_spDeployAppCertificateThumbprint }}
          APP_ID: ${{ secrets.ENV_spDeployAppId }}
          TENANT_ID: ${{ secrets.ENV_spDeployTenantId }}
        run: |
          npm i -g @pnp/cli-microsoft365
          m365 login --authType certificate --certificateBase64Encoded $CERTIFICATE_VALUE --thumbprint $CERTIFICATE_THUMBPRINT --appId $APP_ID --tenant $TENANT_ID
          m365 spo app add --filePath ./packt-solutions-product-management.sppkg -s tenant --overwrite
          m365 spo app deploy --name packt-solutions-product-management.sppkg -s tenant --skipFeatureDeployment